module.exports = {
PORT: 4000,
SOCKET_URL: "http://localhost:3000",
NEW_MESSAGE_EVT: "NEW_MESSAGE_EVT",
NEW_USER_EVT: "NEW_USER_EVT",
PERSON_JOINED_EVT: "PERSON_JOINED_EVT",
PERSON_LEFT_EVT: "PERSON_LEFT_EVT"
}
